In [ ]:
 # @title List

# list ,ordered, mutable,duplicated_allowed
my_list = [1,2,3,4,5,6,7,8,9]
new_list = [1] *5
new_list

# --Slicing
# syntax = [stat_index:stop_index]
my_list[::-1]  #reverse it
my_list[::2] #giving gap of 2

# ---copying a list
org_list = ["ayush",1,3,45,5]
# list_cpy = org_list[:] 1. method
# list_cpy = org_list.copy() 2.
# list_cpy = list(org_list)
# list_cpy


# creating
newlist_1 = list([1,3,4,5,5])
print(type(newlist_1))


# ---list comprehention
comp = [x*2 for x in my_list]
comp

<class 'list'>


[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
 # @title tuple
#tuple,ordered,immutable,allows duplicated
my_tuple = ("agu") #there should not be a single word the tuple shouls carry a ","
type(my_tuple)

my_tuple_1 = ("agu",1,2,True)
my_tuple_1


# --- creating a tuple
create = tuple(['heelo','i','am','tuple'])
create

# -----acessing
create[0]

#----iterables
if 'i' in create:
  print("i")

for i in create:
  print(i)

#-----slicing same as list



i
heelo
i
am
tuple


In [ ]:
#time and space complexity of tuple and python
import sys
import timeit

lt = [1,2,3,4,5]
tp = (1,2,3,4,5)
print(f'list sixe : {sys.getsizeof(lt),"bytes"}')
print(f'tuple sixe : {sys.getsizeof(tp),"bytes"}')

print({f'list time : {timeit.timeit(stmt="[1,2,3,4,5]",number=100000)}'})
print(f'tuple time : {timeit.timeit(stmt="(1,2,3,4,5)",number=100000)}')

print("conclusion tuple is fast and efficient")


list sixe : (104, 'bytes')
tuple sixe : (80, 'bytes')
{'list time : 0.0045013419999690996'}
tuple time : 0.0008565170000451872
conclusion tuple is fast and efficient


In [ ]:
# @title Dictionary
#Dictionary : key-value pairs ,unordered,mutable
# for creating
mydict = {'name':'ayush','age':19}
print(mydict)


mydict1 = dict(name="ayush",age=19)
mydict1

# testing mutability
mydict1['email'] = 'ayushaiml14@gmail.com'
mydict1

# for deleting
del mydict1['age']
mydict1.pop('name')
mydict1

# acessing
for keys in mydict1.keys():
  print(keys)
for value in mydict1.values():
  print(value)
for keys, value in mydict1.items():
  print(keys,value)


#copying
# newdict = mydict1.copy() 1.
newdict = dict(mydict1) #2.
newdict['copy'] = True
newdict

#updating
my_dict_2 = dict(ayush="name")
mydict1.update(my_dict_2)
mydict1


#we can make tuple as a key
mytuple = (8,6)
mydict_tuple = {mytuple:14}
print(mydict_tuple)

# #we can not do this with list because it is mutable and hence unhashable

# In Python, hashable objects have a fixed hash value and can be used as keys in dictionaries
# or elements in a set.
# A list cannot be hashed because its contents can change.

{'name': 'ayush', 'age': 19}
email
ayushaiml14@gmail.com
email ayushaiml14@gmail.com
{(8, 6): 14}


In [ ]:
# @title Set
# set , unordered,mutable,no duplicate
# Ordered vs. Unordered in Python
# 🔹 Ordered → Elements maintain their order of insertion.
# 🔹 Unordered → Elements do not have a fixed order.

myset = {1,2,3,4,5}
print(myset)

# -------creation
# mynewset = set([1,2,3,4])
mynewset = set('Ayush')
mynewset

# -----types
# typeSet = {}  #it dictionary
typeSet = set()
type(typeSet)

#testing mutablity
mynewset.add(12)
mynewset.remove("A")
mynewset

# trashing methods
# remove()
# discard()
# clear()
# pop()

# iterating
for i in mynewset:
  print(i)


# __________union ,intersection,differnce they create new set
odd = {1,3,5,7,9}
even = {2,4,6,8}
prime = {2,3,5,7,9}

Un = odd.union(even)
print(Un)

inter = odd.intersection(prime)
print(inter)

diff = odd.difference(prime)  #give for only odd
print(diff)

diff = odd.symmetric_difference(prime)  #give for both odd and even
print(diff)


# for inplace
odd.update(even)
print(odd)
odd.intersection_update(even)
print(odd)
odd.difference_update(even)
print(odd)

odd.symmetric_difference_update(even)
print(odd)


# __________subset
print(odd.issubset(prime))
print(odd.issuperset(prime))
print(odd.isdisjoint(prime)) #elements diff in bool



# coping
# .copy()
# set()

# frozenset it is immutable version of set
frzSet = frozenset([1,3,45,3])
frzSet_1 = frozenset([1,3,45,3,3,45,23,])
print(frzSet)
# frzSet.union(frzSet_1) all update method work

{1, 2, 3, 4, 5}
u
y
12
h
s
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{9, 3, 5, 7}
{1}
{1, 2}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{8, 2, 4, 6}
set()
{8, 2, 4, 6}
False
False
False
frozenset({1, 3, 45})


In [ ]:
print("-----------for set")
print(sys.getsizeof({1,2,3,4}))
print(timeit.timeit(stmt='{1,2,3,4,5}',number = 100000))
print("-----------for frozenset")
print(sys.getsizeof(frozenset([1,3,45,3])))
print(timeit.timeit(stmt='frozenset([1,3,45,3])',number = 100000))

-----------for set
216
0.009116172999995342
-----------for frozenset
216
0.013538806000042314


In [ ]:
 # @title string
# string is immutable , ordered,text representation
myString = "hello Ayush"
for i in myString:
  print(i)

myString[1:5] # just like list
myString[::-1]

sentence = myString + " " + "how's you day"
sentence

# methods
demo = '   hello pagu   '
var1 = demo.strip()
print(var1.startswith('hello'))
print(var1.endswith('u'))
print(var1.upper())
print(var1.find('a'))
print(var1.replace('pagu','daru'))


demo2 = "hello,my,name,is,agu"
demolt = demo2.split(',')
demolt_string = ' '.join(demolt) #it is faster as compare to formal for loop
demolt_string


#formating
# %   .format  f-string
var = 3.132244
var_1 = "testing"
# my_string = "the varible is %.2f"%var
# my_string = "the variable is {:.2f} and {}".format(var,var_1)
my_string = f"the variable is  {var} and {var_1}"
print(my_string)

h
e
l
l
o
 
A
y
u
s
h
True
True
HELLO PAGU
7
hello daru
the variable is  3.132244 and testing


In [ ]:
# @title Collections
# collections : Counter , namedtuple , OrderedDict , defaultdict , deque

from collections import Counter # it stores counter of unique elements as keys
CounterTest = "aaaabbbbccc1111"
my_counter = Counter(CounterTest)
print(my_counter)
print(my_counter.most_common(1))
print(list(my_counter.elements()))


# just experiment
# my_counter = dict(my_counter)
# for keys,value in my_counter.items():
#   print(keys,value)



from collections import namedtuple  #creates a lightweight, immutable data structure similar to a regular tuple but with named fields

# creating namedtuple class
game = namedtuple("game",['score','type','genre'])

# creating instance of that namedtuple class
g1 = game(score = 9,type='shooting',genre='battleRoyal')
print(g1)
print(g1[0])

print('--------------------------------------')
from collections import  OrderedDict #just as regular dict but is ordered but now regular dict also have ordered
Ordered_Dict = OrderedDict()
Ordered_Dict['a'] = 1
Ordered_Dict['b'] = 2
Ordered_Dict['c'] = 2
print(Ordered_Dict)
print('--------------------------------------')


from collections import  defaultdict #just as regular dict but it has return default value when keys if is not present

default_dict = defaultdict(int)
default_dict['one']=1
default_dict['two']=2
default_dict['three'] #return 0 not a error easy way for try and catch in dict
print(default_dict)
print('--------------------------------------')

from collections import  deque #operating from both side

d = deque()
d.append(1)
d.append(2)
d.appendleft('first')
print(d)

d.rotate(-1) #rotate just like list '[::-1]'
d.rotate(2) #rotate last 2 to first 2
print(d)


d.pop()
d.popleft()
print(d)



Counter({'a': 4, 'b': 4, '1': 4, 'c': 3})
[('a', 4)]
['a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'c', 'c', 'c', '1', '1', '1', '1']
game(score=9, type='shooting', genre='battleRoyal')
9
--------------------------------------
OrderedDict([('a', 1), ('b', 2), ('c', 2)])
--------------------------------------
defaultdict(<class 'int'>, {'one': 1, 'two': 2, 'three': 0})
--------------------------------------
deque(['first', 1, 2])
deque([2, 'first', 1])
deque(['first'])


In [ ]:
# @title itertools
# itertools : product . permutations,combinations,accumulate,groupby,and infinite iterators

from itertools import product # it return a cartesion product
l1 = [1,2,3]
l2 = [5,6,7,8]
prod = product(l1,l2)
print(dict(prod))  #you can print it with any iterable

print("------------------")

from itertools import permutations  #Permutations → Same pairs can repeat in different orders (order matters).
# itertools.permutations(iterable, r)
per = permutations(l1,2)
print(list(per))


from itertools import combinations  #Combinations → No duplicate pairs (order doesn’t matter).

# itertools.combinations(iterable, r)
com = combinations(l1,2)
print(list(com))


from itertools import accumulate #give progressive accumultion
import operator
sumAccum = accumulate(l1)
print(list(sumAccum)) #every no. is the add of previos no.
mulAccum = accumulate(l1, operator.mul)
print(list(mulAccum)) #every no. is the multiply of previos no.


from itertools import groupby  #group similar elment

data = [1, 1, 2, 2, 3, 3, 3, 4, 4, 5]
grp= groupby(data)
for key , gr in grp:
  print(key,list(gr))

#  Infinite Iterators (count(), cycle(), repeat())
from itertools import count,cycle,repeat #carefully thses generate infinte sequence
print("----------")
for i in count(2,5): #start from 2 with 5 increment
  print(i)
  if i > 10:
    break
print("----------")
counter = 0
for i in cycle(['a','b','c']): #infinte over a list
  print(i)
  counter+=1
  if counter >10:
    break

print("----------")
for i in repeat("Ayush",5): #repeat the value
  print(i)



{1: 8, 2: 8, 3: 8}
------------------
[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]
[(1, 2), (1, 3), (2, 3)]
[1, 3, 6]
[1, 2, 6]
1 [1, 1]
2 [2, 2]
3 [3, 3, 3]
4 [4, 4]
5 [5]
----------
2
7
12
----------
a
b
c
a
b
c
a
b
c
a
b
----------
Ayush
Ayush
Ayush
Ayush
Ayush


In [ ]:
# @title lambda  - One liner Anonymous Function
#lambda argument:expression

mul = lambda x,y: x*2
mul(12,3)
lt_3 = [(1,2),(2,8),(4,5)]
sorted_mth = sorted(lt_3,key=lambda x:x[0]+x[1])
sorted_mth
print('-----------')

lt_4 = [1,23,4,34,4]
# map(function,seq)  for every element
map_mth = map(lambda x : x*2,lt_4)
print(list(map_mth))
print('-----------')
# filter(function,seq) filter the element
fil_mth = filter(lambda x : x%2 ==0,lt_4)
print(list(fil_mth))

# reduce(function,seq)  reducing it to a single value
from functools import reduce
red_mth = reduce(lambda x,y:x*y,lt_4)
print(red_mth)


-----------
[2, 46, 8, 68, 8]
-----------
[4, 34, 4]
12512


In [ ]:
# @title Exeption and error
# try-except	Catch exceptions to prevent crashes
# try-except-else	Runs code only if no exception occurs
# try-except-finally	Always runs cleanup code (even after errors)
# Multiple except	Catches specific exceptions
# Catch Exception	Catches any error
# raise	Manually triggers exceptions
# Custom Exceptions	Define your own error types

In [ ]:
# @title Logging
import logging

# logging.basicConfig(level=logging.INFO,filename='log.log',filemode='w',force=True)
# this is the logging.basicConfig that set level from where we have to print log, DEBUG give all logs.
# now formating our logging config
logging.basicConfig(level=logging.DEBUG,filename='log.log',filemode='w',force=True,format="%(asctime)s-%(levelname)s-%(message)s")
# for more formating use python doc



# levels of debuging  in order
logging.debug("debug") #no output
logging.info('info') #no output
logging.warning('warning') #Output starts from  here
logging.error('error')
logging.critical('critical')


# variable logging
x = 69
logging.warning(f'warning there is a {x}')

# exception logging
try :
  69/0
except ZeroDivisionError as e:
  logging.error('ZeroDivisionError',exc_info=True)
  # logging.exception(ZeroDivisionError)
  #both do the same but exception donot need exc_info


#custom logging
# initializing out new log
logger = logging.getLogger(__name__)
# `__name__` is the name of the current module, helping to create a unique logger for each file. 🚀
# makeing a seperate file for our logger
handler = logging.FileHandler("custom.log") #making a file
fomatter = logging.Formatter("%(asctime)s-%(name)s-%(levelname)s-%(message)s") #creating a formatter for our file
handler.setFormatter(fomatter) #assigning the formatter to handler

logger.addHandler(handler) #assigning the handler to our logger
# logging begin now
logger.info("this is custom logging")

In [ ]:
# @title JSON
# Json javascript object notation  light weight data exchange
# Python	     JSON
# dict	   ->    object
# list, tuple	->  array
# str	      ->    string
# int, long, float -> 	number
# True	 ->        true
# False	 ->        false
# None	 ->        null

import json
# converting a dictionary to json file
person = {'age': 30, 'city': 'New York', 'hasChildren': False, 'name': 'John', 'titles': ['engineer', 'programmer']}

personJson = json.dumps(person)
personJson
# saving it in a file
with open("madeJson.json",'w') as f:
  json.dump(person,f,indent=4)


#convering json back to python object
personPythonObject = json.loads(personJson)
personPythonObject


# custom object



{'age': 30,
 'city': 'New York',
 'hasChildren': False,
 'name': 'John',
 'titles': ['engineer', 'programmer']}

In [ ]:
# @title Random Numbers

# the random module _____________________________________________________________
import random


# random float in [0,1)
a = random.random()
print(a)

# random float in range [a,b]
a = random.uniform(1,10)
print(a)

# random integer in range [a,b]. b is included
a = random.randint(1,10)
print(a)

# random integer in range [a,b). b is excluded
a = random.randrange(1,10)
print(a)

# random float from a normal distribution with mu and sigma
a = random.normalvariate(0, 1)
print(a)

# choose a random element from a sequence
a = random.choice(list("ABCDEFGHI"))
print(a)

# choose k unique random elements from a sequence
a = random.sample(list("ABCDEFGHI"), 3)
print(a)

# choose k elements with replacement, and return k sized list
a = random.choices(list("ABCDEFGHI"),k=3)
print(a)

# shuffle list in place
a = list("ABCDEFGHI")
random.shuffle(a)
print(a)


# reproduce numbers with random.seed() ______________________________________________
# Ensures the same random output every time (useful for debugging, testing, and reproducibility).
print('Seeding with 1...\n')

random.seed(1)
print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 42...\n')
random.seed(42)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))



# create cryptographically strong random numbers with the secrets module __________________

# generating cryptographically secure random numbers, mainly for passwords, tokens, and security-related purposes
import secrets
print(secrets.token_hex(16))
print(''.join(secrets.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789") for _ in range(8)))


# create random nd arrays with numpy.random______________________________
# Create random numbers for nd arrays.
import numpy as np

np.random.seed(1)
print(np.random.rand(3))
# generate nd array with random integers in range [a,b) with size n
print(np.random.randint(0,5,(2,3)))
# values from standard normal distribution with mean 0.0 and standard deviation 1.0
print(np.random.randn(5))
# randomly shuffle a nd array.
# only shuffles the array along the first axis of a multi-dimensional array
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.random.shuffle(arr)
print(arr)



0.24489185380347622
2.255841356726295
2
9
-1.2258167276173486
A
['B', 'D', 'I']
['E', 'A', 'B']
['H', 'F', 'A', 'C', 'E', 'D', 'B', 'G', 'I']
Seeding with 1...

0.13436424411240122
8.626903632435095
B

Re-seeding with 42...

0.6394267984578837
1.2250967970040025
E
8c4c9a9b77e9e0d35ecbb363b0d63668
29Y2YD9m
[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[[3 0 0]
 [1 4 4]]
[ 0.86540763 -2.3015387   1.74481176 -0.7612069   0.3190391 ]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [38]:
from os import name
# @title Decorator

def iModify(func):
  def greet(x):
    print("hello")
    result =  func(x)   #for argument we nedd to return it
    return result
  return greet

@iModify
def modeifyMe(x):
  return x*2

rs = modeifyMe(2)
print(rs)

# @ property decorators
# @ property decorator helps us to access private attributes by making getter method and we can change the outcome of attributes by setter method


class propertyTrial:
  def __init__(self,fruit):
    self._fruit = fruit   #made this private

  @property
  def fruit(self):
    '''ItsGetterMethod'''
    print("A getter is called")
    return self._fruit

  @fruit.setter
  def fruit(self,name):
    if isinstance(name,str):
      self_fruit = name
    else:
      raise ValueError("not my fruit")

  @fruit.deleter
  def fruit(self):
    print('deleted')
    del self._fruit


property_1 = propertyTrial('banana')
print(property_1.fruit)
# property_1.fruit = 69
print(property_1.fruit)
del property_1.fruit



#@ staticmethod
# When you need a function inside a class, but it doesn’t depend on instance (self) or class (cls) variables.

class mathoperation:
  @staticmethod
  def add(x,y):   #just like a normal function
    return x+y

print(mathoperation.add(67,2)) #see simply called it like an object
# or you can call it like instance also your choice
obj = mathoperation()
print(obj.add(2,3))

# @ class method
# used to change class level attributes and use cls intead of self

class suboperation:
  num = 23
  @classmethod
  def add(cls,n):   #just like a normal function
    cls.num = n
print(suboperation.num)
suboperation.num = 69
print(suboperation.num)



# @ functools.cache
# it stores the cache of function result so if same input appear then it will give faster answer
# used in resursive and expensive calculation
import time , functools

starttime = time.time()
@functools.cache
def fibonacci(n):
  print(f'calculating fibonacci {n}')
  if n <=1:
    return n
  return fibonacci(n-1)+fibonacci(n-2)
print(fibonacci(4))
# with caching 0.0001766681671142578
# with caching 0.0002543926239013672
endtime = time.time()
print(endtime-starttime)

# @ data class
# @ dataclass automatically generates methods like __init__, __repr__, and __eq__ for a class, so you don’t have to write them manually.

from dataclasses import dataclass

@dataclass
class person:
  name : str
  age : int

p = person("ayush",19)
print(p)

# no fucking amazing not function method


hello
4
A getter is called
banana
A getter is called
banana
deleted
69
5
23
69
calculating fibonacci 4
calculating fibonacci 3
calculating fibonacci 2
calculating fibonacci 1
calculating fibonacci 0
3
0.00021219253540039062
person(name='ayush', age=19)


In [46]:
# @title generators

# it is a special function that print output one by one and donot store it this makes it faster and it remembers where it left off
def my_generator():
  yield 2
  yield 1

g = my_generator()
# print(next(g))
# print(next(g))
# print(sum(g))
print(sorted(g))


# 🚀 Think of it as a function that "remembers" and gives values one at a time!

[1, 2]


In [52]:
# @title Threading vs Multiprocessing

# ✅ Threading → Used for I/O-bound tasks (e.g., file reading, API calls).
from threading import Thread

def square_numbers():
    for i in range(1000):
        result = i * i


if __name__ == "__main__":
    threads = []
    num_threads = 10

    # create threads and asign a function for each thread
    for i in range(num_threads):
        thread = Thread(target=square_numbers)
        threads.append(thread)

    # start all threads
    for thread in threads:
        thread.start()

    # wait for all threads to finish
    # block the main thread until these threads are finished
    for thread in threads:
        thread.join()



# ✅ Multiprocessing → Used for CPU-bound tasks (e.g., heavy calculations, ML training).
from multiprocessing import Process
import os


def square_numbers():
    for i in range(1000):
        result = i * i


if __name__ == "__main__":
    processes = []
    num_processes = os.cpu_count()

    # create processes and asign a function for each process
    for i in range(num_processes):
        process = Process(target=square_numbers)
        processes.append(process)

    # start all processes
    for process in processes:
        process.start()

    # wait for all processes to finish
    # block the main thread until these processes are finished
    for process in processes:
        process.join()

# GIL (Global Interpreter Lock) is a mechanism in Python that prevents multiple threads from running Python code at the same time.

In [49]:
# @title Multithreading



In [50]:
# @title Multiprocessing

In [56]:
# @title Function Arguments

# Arguments and parameters______________
# Parameters are the variables that are defined or used inside parentheses while defining a function
# Arguments are the value passed for these parameters while calling a function
def print_name(name): # name is the parameter
    print(name)

print_name('Alex') # 'Alex' is the argument


# Positional and keyword arguments_________________
def foo(a, b, c):
    print(a, b, c)

# positional arguments
foo(1, 2, 3)

# keyword arguments
foo(a=1, b=2, c=3)
foo(c=3, b=2, a=1) # Note that the order is not important here

# mix of both
foo(1, b=2, c=3)

# default arguments________________________________________
def foo(a, b, c, d=4):
    print(a, b, c, d)

foo(1, 2, 3, 4)
foo(1, b=2, c=3, d=100)

# not allowed: default arguments must be at the end
# def foo(a, b=2, c, d=4):
#     print(a, b, c, d)

# Variable-length arguments (*args and **kwargs)_____________________________
# If you mark a parameter with one asterisk (*), you can pass any number of positional arguments to your function (Typically called *args)
# If you mark a parameter with two asterisks (**), you can pass any number of keyword arguments to this function (Typically called **kwargs).

# Forced keyword arguments___________________

# If you write '*,' in your function parameter list, all parameters after that must be passed as keyword arguments
def foo(a, b, *, c, d):
    print(a, b, c, d)

foo(1, 2, c=3, d=4)
# not allowed:
# foo(1, 2, 3, 4)


# Local vs global variables_____________________
def foo1():
    x = number # global variable can only be accessed here
    print('number in function:', x)

number = 0
foo1()

# modifying the global variable
def foo2():
    global number # global variable can now be accessed and modified
    number = 3

print('number before foo2(): ', number)
foo2() # modifies the global variable
print('number after foo2(): ', number)

# Unpacking into agruments____________________________
def foo(a, b, c):
    print(a, b, c)


# list/tuple unpacking, length must match
my_list = [4, 5, 6] # or tuple
foo(*my_list)

# dict unpacking, keys and length must match
my_dict = {'a': 1, 'b': 2, 'c': 3}
foo(**my_dict)

# my_dict = {'a': 1, 'b': 2, 'd': 3} # not possible since wrong keyword



In [57]:
# @title The Asterisk (*) Operator

In [60]:
# @title  Shallow vs Deep Copying

# A shallow copy creates a new object, but references the same inner objects.
# If the original object contains mutable objects (like lists, dicts, etc.), modifying them in one copy affects the other.

import copy

original = [[1, 2, 3], [4, 5, 6]]
shallow = copy.copy(original)  # Creates a shallow copy

shallow[0][0] = 99  # Modifying the first element

print("Original:", original)  # Also modified!
print("Shallow:", shallow)


# A deep copy creates a completely independent copy, including all nested objects.
# Modifying one does not affect the other.
import copy

original = [[1, 2, 3], [4, 5, 6]]
deep = copy.deepcopy(original)  # Creates a deep copy

deep[0][0] = 99  # Modifying the first element

print("Original:", original)  # Not modified!
print("Deep:", deep)




Original: [[99, 2, 3], [4, 5, 6]]
Shallow: [[99, 2, 3], [4, 5, 6]]
Original: [[1, 2, 3], [4, 5, 6]]
Deep: [[99, 2, 3], [4, 5, 6]]


In [59]:
 # @title Context Managers



